AqueductHub/aqueductcore

aqueductcore/backend/routers/files.py, poetry.lock, pyproject.toml, tests/unittests/test_files.py
This PR adds the validation step for the file name input to the file APIs. Unit tests are in place to cover the changes. A small addition is excluding frontend source code (uncompiled raw) from the Python package build, configured in the toml file.
=> fix(files): Add validation for file names to the files API

aqueductcore/backend/context.py, aqueductcore/backend/errors.py, aqueductcore/backend/models/experiment.py, aqueductcore/backend/models/orm.py, aqueductcore/backend/routers/auth.py, aqueductcore/backend/routers/files.py, aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py, aqueductcore/backend/routers/graphql/mutations_schema.py, aqueductcore/backend/routers/graphql/query_schema.py, aqueductcore/backend/routers/graphql/resolvers/experiment_resolver.py, aqueductcore/backend/routers/graphql/resolvers/tags_resolver.py, aqueductcore/backend/routers/graphql/types.py, aqueductcore/backend/services/experiment.py, aqueductcore/backend/services/utils.py, tests/unittests/initial_data.py, tests/unittests/test_experiment_services.py, tests/unittests/test_files.py, tests/unittests/test_graphql_mutations.py, tests/unittests/test_graphql_queries.py
This PR adds permissions processing retrieved from the tokens in the service layer. The dependency injection system of FastAPI is used to propagate the scopes of the users down to the service layer to implement the business logic of permission-based access for the single user. In the core version, the token is not validated, however, in the pro version, I have implemented the required functionality for the tokens and users.
=> feat(security)!: Permission based access to the API via authentication tokens

aqueductcore/backend/context.py, aqueductcore/backend/routers/graphql/query_schema.py, aqueductcore/backend/routers/graphql/resolvers/experiment_resolver.py, aqueductcore/backend/routers/graphql/types.py, tests/unittests/test_experiment_services.py, tests/unittests/test_files.py, tests/unittests/test_graphql_mutations.py, tests/unittests/test_graphql_queries.py
This PR adds a new node to the GraphQL endpoint that returns the username and scopes from the provided token. The following snippet shows the available query.
```
query TestQuery {
getCurrentUserInfo {
scopes
username
}
}
```
`username` is a string type, and `scopes` is a list of string. The following screenshot shows the GraphiQL execution:
=> feat(user): Add `UserInfo` node to the GraphQL endpoint to return username and scopes.

.github/workflows/pull_request.yaml, aqueductcore/frontend/.eslintignore, aqueductcore/frontend/.eslintrc.js
Due to a new Major release of ESLinst, we're sticking to the Package.json version of ESLIt in this PR.
But it'll be updated in upcoming PRs.
=> fix(eslint): keep version 8

README.md
This PR adds the information about the name of the docker image used for development on the README.md file. Later, once we have a developer section in the docs, this could be added there too, but at this time the docs only contain release information.
=> fix(readme): Add links for `aqueductcore-dev` images on Dockerhub to README.md

README.md
Fix file name to start the aqueduct core service in the readme file.
=> fix(readme): fix start script

.github/workflows/license_report.yml, aqueductcore/frontend/package.json, ci/generate_license_report.sh, ci/license-report-config.json, ci/license_report_template.md
This PR adds the required workflow and scripts to generate license reports for only the production Python and Node.js packages as markdown reports. The generated file is uploaded as an artifact to the action and it is triggered manually.
=> feat(ci): License report Github action and scripts

aqueductcore/backend/models/plugin.py, aqueductcore/backend/routers/graphql/types.py, aqueductcore/backend/services/plugin_executor.py, plugins/python-example/manifest.yml, plugins/python-example/requirements.txt, tests/unittests/test_plugin_executor.py, tests/unittests/test_plugins.py
This code adds a few actions, which happen by default for each plugin at first start:
1. venv in created, if doesn't exist
2. if `requirements.txt` is present, `$venv-python -m pip install -r requirements.txt`
3. If `pyproject.toml` is present, `$venv-python -m pip install .`
$python variable is used in scripts to point to a venv python.
=> feat(plugins): #91 natural support of venv's and requirements.

aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
Fix pagination reset issue when changing to Favourite and Archive
=> fix(router): change category resets pagination

aqueductcore/__init__.py, aqueductcore/backend/errors.py, aqueductcore/backend/services/experiment.py, aqueductcore/cli/export.py, aqueductcore/cli/exporter.py, aqueductcore/cli/importer.py, aqueductcore/cli/models.py, aqueductcore/cli/session.py, poetry.lock, pyproject.toml, tests/unittests/cli/conftest.py, tests/unittests/cli/test_export.py, tests/unittests/cli/test_exporter.py, tests/unittests/cli/test_importer.py
This PR adds the import and export modules to the CLI application for importing aqueduct artifacts that are previously exported. Tests are added to check the functionality. The following describes the importing behaviour in certain scenarios:
- When importing, if there is an existing experiment with the same experiment ID (aka alias), the import fails, outputting the conflicting experiments.
- When importing, if there are already existing conflicting tags, the existing ones will be used to be assigned to the imported experiment. This means the original display case (name field) will be preserved.
- When importing, if the are already existing conflicting users with the same user ID, the original username will be kept and the experiments will be assigned to the existing user. Conflicting …
=> feat(cli): Modules to import/export metadata and experiment files into the Aqueduct instance

aqueductcore/frontend/src/__mocks__/ExtensionsDataMock.ts, aqueductcore/frontend/src/__mocks__/constants.ts, aqueductcore/frontend/src/__mocks__/mutations/extension/executeExtension.tsx, aqueductcore/frontend/src/__mocks__/queries/experiment/getExperimentByIdMock.tsx, aqueductcore/frontend/src/__tests__/Extensions.test.tsx, aqueductcore/frontend/src/components/atoms/ExperimentField/index.tsx, aqueductcore/frontend/src/components/atoms/FileField/index.tsx, aqueductcore/frontend/src/components/atoms/FloatField/index.tsx, aqueductcore/frontend/src/components/atoms/IntegerField/index.tsx, aqueductcore/frontend/src/components/atoms/SelectField/index.tsx, aqueductcore/frontend/src/components/atoms/TextAreaField/index.tsx, aqueductcore/frontend/src/components/atoms/TextInputField/TextInputField.test.tsx, aqueductcore/frontend/src/components/atoms/TextInputField/index.tsx, aqueductcore/frontend/src/components/atoms/sharedStyledComponents/ExtensionInputFields/index.tsx, aqueductcore/frontend/src/components/molecules/ActionForm/index.tsx, aqueductcore/frontend/src/components/molecules/ExtensionActions/index.tsx, aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
* Add field hints to show type of data to be filled.
* Disabling `RUN EXTENSION` button till the required fields are not filled.
* Fix dark mode failures in extension modal.
=> feat(enhanced-extension): add validation and dark theme support to extension modal

containers/release-azure/entrypoint.sh, containers/release/Dockerfile
This PR Set the number of workers for the release docker images to 4 to fix the issue with running extensions blocking the server thread from handling new requests.
=> fix(docker): Set the number of workers for release docker images to 4.

aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
* added error message in the `recents`, `archived` and `favourites` pages in case of no experiments in the list.
=> feat(empty-list-message): added error message for empty experiment list page

docs/setup.md
This PR edits an example compose file. Fixes some issues with extensions, adds volume to postgres, and gives some advises about setting the values.
=> fix(compose): editing compose file and add setup hints

aqueductcore/frontend/src/components/atoms/sharedStyledComponents/VisuallyHiddenInput/index.tsx, aqueductcore/frontend/src/components/organisms/Attachments/Explorer/index.tsx, aqueductcore/frontend/src/components/organisms/Attachments/index.tsx, aqueductcore/frontend/src/components/templates/UploadFileZone/index.tsx, aqueductcore/frontend/src/hooks/useUploadFile.test.ts, aqueductcore/frontend/src/hooks/useUploadFile.ts
Uncomment upload button and let users upload files for experiments
=> feat(upload): add upload button functionality

aqueductcore/frontend/src/__tests__/Extensions.test.tsx, aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx, aqueductcore/frontend/src/types/componentTypes.ts, containers/dev/docker-compose.yaml
* extension modal submit button now functions as a form
* add test for data persistence
* Keep the data while changing between actions(FKA functions)
* On successful execution of the function form data should be cleared
* It should be a Form with onSubmit and pressing enter as a submission
=> feat(data-persistence): Added data persistence on switching between different functions

README.md, scripts/release/README.md, scripts/release/docker-compose.yaml, scripts/release/install.sh
This PR updates the reference docker-compose to add celery worker and flower alongside rabbitmq. Traefik reverse proxy is also added to let the user access different services via the host address `*.localhost`. Traefik automatically handles this DNS addition to the host, which I found very interesting! We might later change it but it is a good starting point.
=> fix(docker): Update reference release docker compose

aqueductcore/backend/models/extensions.py, aqueductcore/backend/routers/graphql/mutations_schema.py, aqueductcore/backend/routers/graphql/query_schema.py, aqueductcore/backend/services/extensions_executor.py, aqueductcore/backend/services/task_executor.py, tests/integration/test_extensions_executor.py, tests/integration/test_graphql_mutations.py, tests/integration/test_task_executor.py
This PR adds and endpoint for task cancellation. A few things to note:
1. According to functional specification, we should expect KeyboardInterrupt exception (SIGINT), but this this signal task is not cancelled: it changes status to REVOKED, and then, after process is finished,  becomes successful. To actually kill the job SIGTERM and SIGKILL are suitable.
2. There are a few comments left, that after implementation of persistence, some code should be added to populate `TaskInfo` objects.
3. TaskExecutor and mutation call tests added.
=> feat(task-cancel): task cancellation endpoint

aqueductcore/backend/services/extensions_executor.py
This PR takes care that a token is propagated to the extension as `$API_TOKEN` environment variable.
=> fix(jobs): stop overriding a token - TT-89

aqueductcore/backend/context.py, aqueductcore/backend/models/orm.py, aqueductcore/backend/models/task.py, aqueductcore/backend/routers/files.py, aqueductcore/backend/routers/graphql/resolvers/task_resolver.py, aqueductcore/backend/routers/graphql/types.py, aqueductcore/backend/services/experiment.py, aqueductcore/backend/services/extensions.py, aqueductcore/backend/services/extensions_executor.py, aqueductcore/backend/services/task_executor.py, aqueductcore/backend/services/utils.py, aqueductcore/frontend/src/__mocks__/queries/user/getUserInformation.tsx, aqueductcore/frontend/src/helper/auth/userScope.tsx, poetry.lock, tests/conftest.py, tests/integration/test_graphql_experiment_queries.py, tests/integration/test_graphql_tasks.py, tests/integration/test_job_scopes.py, tests/unittests/initial_data.py, tests/unittests/test_job_scopes.py
Based on: https://riverlane.atlassian.net/wiki/spaces/Tooling/pages/3319070744/ERD+Job+Queuing+--+Aqueduct+Pro+scopes
🟢 ERD1.1-1B
- in `get_all_tasks` was originally supported
🟢 ERD1.1-2B
- in `get_all_tasks` was originally supported
🟢 ERD1.3-1B
- added to `orm.py` and `extensions.py`
⚪ ERD1.3-2F - TBD
⚪ ERD1.3-3F - TBD
🟢 ERD2.1-1B 
- `aqueductcore/backend/context.py`
⚪ ERD2.1-2B - this is a Core changes.
🟢 ERD2.1-3F 
- `aqueductcore/frontend/src/__mocks__/queries/user/getUserInformation.tsx`
- `aqueductcore/frontend/src/helper/auth/userScope.tsx`
⚪ ERD2.1-4F - Pro changes here
🟢 ERD2.2-1B
- added to `get_all_tasks`
🟢 ERD2.2-2B
- added to `get_all_tasks`
🟢 ERD2.2-3B
- added to `get_all_tasks`
🟢 ERD2.2-4B
- added to `get_all_tasks`
🟢 ERD2.3-2B 
- added to execute() of …
=> feat(tasks): supporting scopes in tasks TT-114

aqueductcore/backend/services/task_executor.py
If extension process has a return code != 0, raise a `ChildProcessError` and then handle this at the `update_task_info` level. Treat arguments of exception as result.
=> fix(cancellation): adding failure processing

aqueductcore/frontend/src/__mocks__/queries/tasks/getAllTasks.tsx, aqueductcore/frontend/src/components/organisms/TaskListInExperimentDetails/index.tsx, aqueductcore/frontend/src/components/organisms/TasksListTable/index.tsx, aqueductcore/frontend/src/constants/constants.ts
Fix previous commit to not change all tables
=> feat: TT-166 task list redesign

aqueductcore/backend/services/experiment.py, aqueductcore/backend/services/task_executor.py
* On deleting experiment, all tasks related to the task get deleted.
* Removal of task rows from the Task table.
* Removal of results, status and everything related to the tasks.
=> feat(task-cleanup): Deletion of experiment deletes all tasks related to it

aqueductcore/frontend/src/components/molecules/LogViewer/index.tsx, aqueductcore/frontend/src/components/organisms/ExperimentDetailsActionButtons/index.tsx, aqueductcore/frontend/src/components/organisms/ExperimentDetailsData/index.tsx, aqueductcore/frontend/src/components/organisms/TaskListInExperimentDetails/index.tsx, aqueductcore/frontend/src/helper/functions.tsx, aqueductcore/frontend/src/pages/TaskHistoryPage/index.tsx, aqueductcore/frontend/src/types/componentTypes.ts
- Copy button for EID
- Better look for the Log
- And a letter capitalisation fix
=> feat: quick features
