- docs/getting-started.md
> fix(docs): fix spelling in getting-started.md

- README.md
- alembic/database-migration-guide.md
Cut down and edit README. This version is a simpler entry point for new people.
> fix(docs): Simplify README.

- aqueductcore/frontend/package.json
- aqueductcore/frontend/tsconfig.json
- aqueductcore/frontend/yarn.lock
Make aqueduct-core ready to be released to package managers
> fix(package): update package.json and tsconfig

- aqueductcore/backend/errors.py
- aqueductcore/backend/main.py
- aqueductcore/backend/routers/files.py
- aqueductcore/backend/routers/graphql/inputs.py
- aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py
- aqueductcore/backend/routers/graphql/mutations_schema.py
- aqueductcore/backend/routers/graphql/resolvers/experiment_resolver.py
- aqueductcore/backend/routers/graphql/resolvers/tags_resolver.py
- aqueductcore/backend/routers/graphql/types.py
- aqueductcore/backend/services/experiment.py
- aqueductcore/backend/services/validators.py
- tests/unittests/test_experiment_services.py
- tests/unittests/test_graphql_mutations.py
- tests/unittests/test_graphql_queries.py
- tests/unittests/test_validators.py
Allows users to delete experiments along with their linked files
There are no breaking changes in this PR
> feat(delete_experiment): add feature to delete experiment

- aqueductcore/frontend/codegen.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/fragment-masking.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/gql.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/graphql.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/index.ts
Update GraphQL generated types
> feat(api): generate new Graphql API types

- aqueductcore/backend/constants.py
- aqueductcore/backend/context.py
- aqueductcore/backend/models/experiment.py
- aqueductcore/backend/models/orm.py
- aqueductcore/backend/routers/graphql/types.py
- aqueductcore/backend/routers/graphql/utils.py
- aqueductcore/backend/services/experiment.py
- aqueductcore/backend/services/utils.py
- aqueductcore/backend/settings.py
- tests/unittests/initial_data.py
- tests/unittests/test_experiment_services.py
- tests/unittests/test_files.py
- tests/unittests/test_graphql_mutations.py
- tests/unittests/test_graphql_queries.py
Added created_by field in experiment model to enable this field in queries and mutations.
There are no breaking changes in this PR
> feat: Added created_by field in Experiment model

- README.md
> fix(readme): Update README.md

- aqueductcore/backend/settings.py
Added `keycloak_client_id` in settings.py file
> feat(graphql-field): Client ID field as environment variable

- aqueductcore/frontend/src/API/graphql/queries/getUserInformation.tsx
- aqueductcore/frontend/src/App.tsx
- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/getExperimentByIdMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/getUserInformation.tsx
- aqueductcore/frontend/src/__tests__/ExperimentDetailsPage.test.tsx
- aqueductcore/frontend/src/components/molecules/EditTags/index.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentDescription/ExperimentDescription.test.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentDescription/index.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentTitle/ExperimentTitle.test.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentTitle/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
- aqueductcore/frontend/src/context/AuthProvider.tsx
- aqueductcore/frontend/src/helper/auth/userScope.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
- aqueductcore/frontend/tsconfig.json
> feat(security): add scopes logic in the frontend

- aqueductcore/frontend/envs/.env.dev
- aqueductcore/frontend/envs/.env.prod
- aqueductcore/frontend/src/components/templates/drawerLayout/index.tsx
- containers/dev/docker-compose.yaml
- scripts/build_frontend.sh
* Added sidebar item for documentation
* Added link to documentation for the item in sidebar
> feat(documentation-link): Added link to documentation in sidebar

- scripts/build_frontend.sh
* Fixed build_frontend.sh file to use root of production environment files as PROJECT_ROOT variable
> fix(env-root-fix): Updated root of env files to project root

- aqueductcore/frontend/package.json
- aqueductcore/frontend/src/components/organisms/Attachments/Attachments.test.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Explorer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
- aqueductcore/frontend/src/helper/functions.tsx
- aqueductcore/frontend/src/types/componentTypes.ts
to make the list of files in the experimentDetails page sortable.
> feat(table): make file table sortable

- aqueductcore/frontend/src/API/graphql/mutations/Experiment/removeExperiment.tsx
- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/mutations/removeExperimentMock.tsx
- aqueductcore/frontend/src/__mocks__/mutations/updateExperimentMock.tsx
- aqueductcore/frontend/src/__tests__/ExperimentDetailsPage.test.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
- aqueductcore/frontend/src/helper/auth/userScope.tsx
- aqueductcore/frontend/src/pages/ExperimentDetailsPage/index.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
* Added delete experiment button conditionally rendered for archived experiments.
* Added deletion confirmation modal to ask user for confirmation of delete operation.
> feat(remove-experiment-ui): Feature to delete archived experiments in UI

- .github/workflows/pull_request.yaml
- .github/workflows/semantic_pr_title.yaml
Small PR to Fix the execution of workflows on feature branches, following the feature branch naming guide.
> fix(ci): Fix execution of workflows on feature branches

- aqueductcore/backend/routers/files.py
- aqueductcore/backend/services/constants.py
- aqueductcore/backend/services/experiment.py
- aqueductcore/backend/services/utils.py
* Added util method to generate content type for files
* Implemented utility method to send content type in response headers.
> feat(content-type): Content-Type in headers in /api/files

- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/constants.ts
- aqueductcore/frontend/src/__mocks__/mutations/updateExperimentMock.tsx
- aqueductcore/frontend/src/__tests__/ExperimentDetailsPage.test.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentDescription/ExperimentDescription.test.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentTitle/ExperimentTitle.test.tsx
- aqueductcore/frontend/src/components/molecules/FilterTags/TagsDropdown.test.tsx
- aqueductcore/frontend/src/components/molecules/SearchBar/SearchBar.test.tsx
- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
Fix Frontend test warning and errors
Three commits from #89 pull request are cherry-picked in this new PR.
> fix(test): test warnings cleanup

- aqueductcore/frontend/package.json
- aqueductcore/frontend/src/__mocks__/react-markdown.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Attachments.test.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Explorer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
- aqueductcore/frontend/src/helper/formatters.tsx
- aqueductcore/frontend/src/pages/ExperimentDetailsPage/index.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
- aqueductcore/frontend/yarn.lock
- Add markdown Library in the frontend to preview `.md` files
- Also make `text/plain` content type readable in the file Viewer.
> feat: render markdown

- .github/workflows/license_report.yml
- .gitignore
- .vscode/settings.json
- aqueductcore/backend/routers/graphql/inputs.py
- aqueductcore/backend/routers/graphql/mutations/experiment_mutations.py
- aqueductcore/backend/routers/graphql/mutations_schema.py
- aqueductcore/backend/services/experiment.py
- ci/generate_license_report.sh
- ci/unit_tests.sh
- tests/unittests/test_experiment_services.py
- tests/unittests/test_graphql_mutations.py
This PR adds a new mutation to add a list of tags to an experiment. The service method is changed to support that and if there are duplicate tags in the request, an error will be returned following the exception. If the tags were already assigned to an experiment, the service safely continues and adds the new tags to the database and experiment. Unit tests and integration tests are added.
> feat(tags): New mutation to add multiple tags to an experiment.

- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/getAllExperimentsMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/getAllExperimentsWithNameFilterMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/getAllExperimentsWithTagFilterMock.tsx
- aqueductcore/frontend/src/__tests__/ExperimentRecordsPage.test.tsx
- aqueductcore/frontend/src/components/molecules/SearchBar/index.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentsListTable/index.tsx
- aqueductcore/frontend/src/components/organisms/FilterExperiments/index.tsx
- aqueductcore/frontend/src/components/templates/drawerLayout/index.tsx
- aqueductcore/frontend/src/helper/functions.tsx
- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
Pagination and Filters are stored in the URL to be persistent during the navigations.
> feat: keep page info in url

- aqueductcore/frontend/src/components/organisms/ExperimentsListTable/index.tsx
- aqueductcore/frontend/src/components/organisms/FilterExperiments/index.tsx
- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
Fix issues with pagination and back button
> fix: pagination in url

- aqueductcore/frontend/src/components/atoms/AqueductLogo/index.tsx
- aqueductcore/frontend/src/components/templates/drawerLayout/index.tsx
- aqueductcore/frontend/src/pages/SettingsPage/index.tsx
Make code more reusable as a dependency
> feat(drawer): make more exportable functions

- .github/workflows/docs_pr_preview.yml
- docs/cli.md
- mkdocs.yaml
This PR adds documentation for Aqueduct CLI with import/export functionality. Also, in this PR, I have enabled the github action to provide PR review for the docs using the Azure instance.
> feat(docs): Add documentation for Aqueduct CLI with import/export functionality

- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
> fix(extension): hide extensions from the experiment details page

- .github/workflows/release.yaml
* update release.yaml file to include generateReleaseNotes attribute
> feat(release-notes): add generateReleaseNotes boolean in release.yaml file

- .github/workflows/automated_release.yaml
Fix output of week check from GITHUB_ENV to GITHUB_OUTPUT
> fix(automated-release): fix saving the output from env to output

- .github/workflows/automated_release.yaml
* add `workflow_dispatch` in automated-release workflow file to allow manual triggering of release
> feat(manual-release): enable manual dispatch of release

- aqueductcore/frontend/src/components/atoms/AqueductLogo/index.tsx
> feat(logo): Link the main logo to the homepage

- aqueductcore/frontend/src/API/graphql/mutations/extension/executeExtension.tsx
- aqueductcore/frontend/src/__mocks__/ExperimentsDataMock.ts
- aqueductcore/frontend/src/__mocks__/mutations/extension/executeExtension.tsx
- aqueductcore/frontend/src/__tests__/Extensions.test.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Explorer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- aqueductcore/frontend/src/context/FileSelectProvider.tsx
- aqueductcore/frontend/src/pages/ExperimentDetailsPage/index.tsx
- aqueductcore/frontend/src/types/componentTypes.ts
- aqueductcore/frontend/src/types/globalTypes.ts
- Select the file from the file list and open it in the content viewer
> feat(files): open log file when extension is executed

- aqueductcore/frontend/src/components/molecules/ActionForm/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- Determine fail and success based on `returnCode`
- Fix checkbox value
> fix: extension stderr

- aqueductcore/backend/context.py
- aqueductcore/backend/models/extensions.py
- aqueductcore/backend/routers/graphql/mutations_schema.py
This PR enables passing API token to the plugin execution environment if exists.
> feat(plugins): Pass API token to the plugin execution environment if exists

- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
Make HTML files viewable in the GUI
> feat(viewer): add html special type to preview

- .github/workflows/automated_release.yaml
- .github/workflows/static_analysis_and_tests.yaml
- README.md
> fix: ci status readme 94

- aqueductcore/frontend/src/components/molecules/ExtensionActions/index.tsx
- aqueductcore/frontend/src/components/organisms/Attachments/Viewer/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- aqueductcore/frontend/src/hooks/useUploadFile.test.ts
- aqueductcore/frontend/src/hooks/useUploadFile.ts
A quick fix when fetch failed due to the issues with the file
> fix(fetch): handle in case some error happened in Fetch

- aqueductcore/frontend/src/API/graphql/queries/experiment/getExperimentFilesById.tsx
- aqueductcore/frontend/src/constants/apolloOptions.tsx
- Fix keyFields after renaming `id`
> fix(graphql): fix keyFields of GraphQL

- aqueductcore/backend/context.py
- aqueductcore/backend/routers/files.py
- aqueductcore/backend/services/utils.py
- tests/unittests/test_files.py
- tests/unittests/test_utils.py
* add router view for removing files from the experiment
* add relevant tests for remove experiment file
> feat(remove-files): add router view for removing files

- aqueductcore/frontend/src/API/graphql/mutations/experiment/createExperiment.tsx
- aqueductcore/frontend/src/API/graphql/mutations/experiment/removeExperiment.tsx
- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/ExperimentsDataMock.ts
- aqueductcore/frontend/src/__mocks__/mutations/experiment/createExperimentMock.tsx
- aqueductcore/frontend/src/__mocks__/queries/experiment/getExperimentByIdMock.tsx
- aqueductcore/frontend/src/__tests__/ExperimentRecordsPage.test.tsx
- aqueductcore/frontend/src/components/atoms/AddButton/index.tsx
- aqueductcore/frontend/src/components/molecules/ExperimentTitle/index.tsx
- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
Create a new Experiment by click a + button in experiments list
> feat(button): add new experiment button

- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
> fix(layout): align items center

- aqueductcore/frontend/src/components/atoms/LinkRenderer/index.tsx
- aqueductcore/frontend/src/components/molecules/ActionForm/index.tsx
- aqueductcore/frontend/src/components/molecules/ExtensionActions/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- Style clean ups for actions list 
- Details are considered as MD files, now we can include MD files in the extensions description
> fix(extension): clean up styles for extensions modal and extensions description as MD file

- tests/unittests/test_extensions_executor.py
- tests/unittests/test_graphql_queries.py
Updated submodule after finished implementation of extensions
> feat(qiskit-extension): submodule updated

- aqueductcore/backend/routers/files.py
Check if the user has access to the experiment via calling the function `get_experiment_by_uuid`.
> fix(permission): fix user permission to remove file

- aqueductcore/frontend/src/API/graphql/mutations/extension/executeExtension.tsx
- aqueductcore/frontend/src/API/graphql/queries/tasks/getAllTasks.tsx
- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/TasksDataMock.ts
- aqueductcore/frontend/src/__mocks__/mutations/extension/executeExtension.tsx
- aqueductcore/frontend/src/__mocks__/queries/tasks/getAllTasks.tsx
- aqueductcore/frontend/src/__tests__/Extensions.test.tsx
- aqueductcore/frontend/src/__tests__/JobHistoryPage.test.tsx
- aqueductcore/frontend/src/components/molecules/JobListTableCells/JobExtensionStatus/index.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentsListTable/ExperimentsListTable.test.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- aqueductcore/frontend/src/helper/formatters.tsx
- aqueductcore/frontend/src/pages/ExperimentRecordsPage/index.tsx
- aqueductcore/frontend/src/pages/JobHistoryPage/index.tsx
- aqueductcore/frontend/src/types/globalTypes.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/gql.ts
- aqueductcore/frontend/src/types/graphql/__GENERATED__/graphql.ts
Even though this PR includes more than just mocks, but the main purpose is to provide Mock data for the frontend test.
> feat(codegen): codegen new GraphQL types

- README.md
fix(readme): how to troubleshoot Linux/arm64 on mac
> fix:  add troubleshoot for Linux/arm64 on mac in readme

- aqueductcore/frontend/src/components/molecules/JobListTableCells/JobExperimentName/index.tsx
- aqueductcore/frontend/src/components/molecules/JobListTableCells/JobExtensionStatus/index.tsx
- aqueductcore/frontend/src/components/organisms/JobDetailsModal/index.tsx
- aqueductcore/frontend/src/theme.ts
* added support for dark mode in job details modal
* update styles in status chips to use theme constants instead of hardcoded values
* apply ellipsis in experiment name in chip in job details page
> feat(job table improvements): apply multiple improvements to jobs UI

- aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
- aqueductcore/frontend/src/pages/JobHistoryPage/index.tsx
Add pagination for the job list
> feat: TT-134 job list pagination

- aqueductcore/frontend/src/API/graphql/queries/tasks/getAllTasks.tsx
- aqueductcore/frontend/src/API/graphql/queries/tasks/getTask.tsx
- aqueductcore/frontend/src/__mocks__/AppContextAQDMock.tsx
- aqueductcore/frontend/src/__mocks__/ExtensionsDataMock.ts
- aqueductcore/frontend/src/__mocks__/TasksDataMock.ts
- aqueductcore/frontend/src/__mocks__/mutations/extension/executeExtension.tsx
- aqueductcore/frontend/src/__mocks__/queries/tasks/getTask.tsx
- aqueductcore/frontend/src/components/atoms/Loading/index.tsx
- aqueductcore/frontend/src/components/molecules/JobListTableCells/JobExperimentName/index.tsx
- aqueductcore/frontend/src/components/molecules/LogViewer/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionModal/index.tsx
- aqueductcore/frontend/src/components/organisms/JobDetailsModal/index.tsx
- aqueductcore/frontend/src/components/organisms/JobsListTable/index.tsx
- aqueductcore/frontend/src/helper/formatters.tsx
- aqueductcore/frontend/src/pages/ExperimentDetailsPage/index.tsx
- aqueductcore/frontend/src/types/componentTypes.ts
- aqueductcore/frontend/src/types/globalTypes.ts
- Make task execution using actual API
- Fix mock data
Left to fix:
- Add `user` form the real API call
> feat: TT-128 task execution

- aqueductcore/backend/services/task_executor.py
- tests/integration/test_job_scopes.py
Making sure, that queries by ID and revoke query work both in tests and in frontend.
> fix(scopes): resolving issues with lazy loading and access control

- aqueductcore/frontend/src/__mocks__/queries/tasks/getAllTasks.tsx
- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
- aqueductcore/frontend/src/components/organisms/ExtensionsList/index.tsx
- aqueductcore/frontend/src/components/organisms/JobListInExperimentDetails/index.tsx
Add job list the experiment details page
> feat(table): add job history in the experiment details page

- aqueductcore/backend/routers/graphql/resolvers/task_resolver.py
This includes a minor change to fix error received while trying to filter tasks by experiment.
> fix(experiment-details): update IDType.UUID from string to imported type

- aqueductcore/frontend/src/components/organisms/ExperimentDetails/index.tsx
Make experiment Tasks as the same level as experiment info
> fix(tasks): redesign task list

- aqueductcore/backend/services/task_executor.py
- poetry.lock
- pyproject.toml
Use SIGINT instead on SIGTERM and allow process to cancel gracefully
> fix(cancellation): TT-168 add graceful cancellation

- aqueductcore/frontend/src/__tests__/TaskDetailsModal.test.tsx
- aqueductcore/frontend/src/components/organisms/TaskDetailsModal/index.tsx
- change cancelation message
- use CircularProgress component instead of loading text
> fix: TT-178-change cancelation message

- aqueductcore/backend/services/extensions.py
* Add user creation block in case of non-existing user before executing extension
> feat(fix-failing-tasks): Update execute method to create non existing user
